version: "3.4"
services:
  api:
    image: docker.pkg.github.com/itwasnoteasy/new-cicd-lab-files/mcw-continous-delivery-api:main
    ports:
      - "3001:3001"

  web:
    image: docker.pkg.github.com/itwasnoteasy/new-cicd-lab-files/mcw-continous-delivery-web:main
    depends_on:
        - api
    environment:
        CONTENT_API_URL: http://api:3001
    ports:
        - "3000:80"
        